### ISSUE TITLE
Title could be simplified

### ISSUE THREAD

**Issue by SteveEvansGDS** [cabinetoffice/gsg-guidance#12]
https://github.com/cabinetoffice/gsg-guidance/blob/5bb34ffa75a7dfe896eff5a793ed09e27cf74264/source/index.html.md.erb#L6

I think we should go for a simpler heading here. Something like “Government security guidance”, “Security guidance for government,” or even “Security guidance” would work better. The focus will be on the content that users are looking for, rather than who is behind it, which better meets the Style Guide and the requirements for writing on GOV.UK.

**Comment by jonodrew** [comment]
Thanks for raising this. However, I'm not sure - other organisations publishing on a subdomain use their org names, eg great.gov.uk or ncsc.gov.uk

**Comment by TechPunk316** [comment]
My two cents. Great.gov.uk is a campaign so we have to be careful to compare our project to this. NCSC is an entire organisation so again it's not quite the same. If it is to be branded it should be with the department - Cabinet Office

Can I suggest we go with "Government security standards and guidance" so it matches what is in the header?
![Screenshot 2021-01-29 at 12 14 30](https://user-images.githubusercontent.com/30231796/106274072-97831c80-622b-11eb-926a-e2dcff4c53eb.png)
